// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA--aF9_0ZUhBfhRL9Qr36gjIAXwqRyEX8',
    appId: '1:786017296280:web:61b030f59cb364037ad5ed',
    messagingSenderId: '786017296280',
    projectId: 'spendify-c09b2',
    authDomain: 'spendify-c09b2.firebaseapp.com',
    storageBucket: 'spendify-c09b2.firebasestorage.app',
    measurementId: 'G-YG1EZY3ZCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8oiKBpGrRqBMDgW1cRmpl2xArX83RStU',
    appId: '1:786017296280:android:a14f7e1abe3a98f67ad5ed',
    messagingSenderId: '786017296280',
    projectId: 'spendify-c09b2',
    storageBucket: 'spendify-c09b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdpTY_tXv4a2fs56MteB07O7pSrsJFQw',
    appId: '1:786017296280:ios:a6d65782af17a4897ad5ed',
    messagingSenderId: '786017296280',
    projectId: 'spendify-c09b2',
    storageBucket: 'spendify-c09b2.firebasestorage.app',
    iosBundleId: 'com.example.spendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdpTY_tXv4a2fs56MteB07O7pSrsJFQw',
    appId: '1:786017296280:ios:a6d65782af17a4897ad5ed',
    messagingSenderId: '786017296280',
    projectId: 'spendify-c09b2',
    storageBucket: 'spendify-c09b2.firebasestorage.app',
    iosBundleId: 'com.example.spendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA--aF9_0ZUhBfhRL9Qr36gjIAXwqRyEX8',
    appId: '1:786017296280:web:566344d663f752b37ad5ed',
    messagingSenderId: '786017296280',
    projectId: 'spendify-c09b2',
    authDomain: 'spendify-c09b2.firebaseapp.com',
    storageBucket: 'spendify-c09b2.firebasestorage.app',
    measurementId: 'G-RV25BD6D1D',
  );
}
